Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [1]:
import pandas as pd
import numpy as np

In [2]:
# First Solution

x = np.array([3,4,5,6])
y= np.vander(x)


y= np.vander(x)
print("The input vecor is: \n",x)
print("---------------------------",)

# When incresing is False -
print("The output matrix: when increasing is False: \n",y)
print("---------------------------",)

#When increasing is True
z=np.vander(x,increasing=True)
print("The output matrix : when increasing is True: \n",z)

The input vecor is: 
 [3 4 5 6]
---------------------------
The output matrix: when increasing is False: 
 [[ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]]
---------------------------
The output matrix : when increasing is True: 
 [[  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]]


In [3]:
# Second Solution 

def output_matrix(input_matrix, n,increasing):
    if not increasing: 
        output_matrix = np.array([j**(n-1-i) for j in input_matrix for i in range(n)]).reshape(len(input_matrix),n)
    else:
       output_matrix = np.array([j**i for j in input_matrix for i in range(n)]).reshape(len(input_matrix),n)
    return output_matrix

x = np.array([3,4,5,6])
n=4

print("The input vecor is: \n",x)
print("---------------------------",)

y = output_matrix(x,4,False)
print("The output matrix: when increasing is False: \n",y)
print("---------------------------",)

z = output_matrix(x,4,True)

print("The output matrix : when increasing is True: \n",z)
print("---------------------------",)

The input vecor is: 
 [3 4 5 6]
---------------------------
The output matrix: when increasing is False: 
 [[ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]
 [216  36   6   1]]
---------------------------
The output matrix : when increasing is True: 
 [[  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]
 [  1   6  36 216]]
---------------------------


Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [5]:
# The moving average sequence is n-k+1, so mode will be 'valid'

def moving_avg(input_array, k):
    n = len(input_array)
    output_array = np.ones(n-k+1)
    for i in range(len(output_array)):
        output_array[i] = np.sum(input_array[0:k])/k 
        print("The Moving Average is : ", output_array[i])
        input_array = np.roll(input_array,-1)
    

input_array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
print("The input array is: ",input_array)
print("\n")
print("K value is: ",k)
print("\n")

moving_avg(input_array, 3)

The input array is:  [  3   5   7   2   8  10  11  65  72  81  99 100 150]


K value is:  3


The Moving Average is :  5.0
The Moving Average is :  4.666666666666667
The Moving Average is :  5.666666666666667
The Moving Average is :  6.666666666666667
The Moving Average is :  9.666666666666666
The Moving Average is :  28.666666666666668
The Moving Average is :  49.333333333333336
The Moving Average is :  72.66666666666667
The Moving Average is :  84.0
The Moving Average is :  93.33333333333333
The Moving Average is :  116.33333333333333
